spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mentoring?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: h25189230!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

auth:
  jwt:
    secret: gkgpfud
    header: Authorization
    prefix: Bearer
    exp:
      access: 1800
      refresh: 640800